### ISSUE TITLE
Pass the resolved value of a promise to the next step

### ISSUE THREAD

**Issue by pedro93** [IndigoUnited/node-planify#21]
Hello,

I was trying out this library and I'm having a hard time trying to figure something out. Could you point me in the direction or tell me what I'm doing wrong?

```js
planify({ exit: true, reporter: argv.reporter })
    .step('Compiling server', () => {
        return buildServer({ env: 'dev' }); // in essence its return (resolve(function(){render...}
    })
    .step('Running server', (func) => { console.log('after', func); })
    .run();
```

I this code snippet I'm trying to build a server (webpack compilation) which is a promise function. 

buildServer will resolve with a function, which I want to pass on to the next step. However I have been unable to do so. 

I have tried with the data parameter in the step function but I received a pending promise. Is there no way to have planify wait for the promise to resolve/reject?

Thanks for taking the time to read this :)

**Comment by satazor** [comment]
Hello!

Each step receives a `data` argument which is an object you can fill with data. This argument is the same along the step chain. You may find an example in the README.

Let me know if this helps.

**Comment by pedro93** [comment]
I did what you mentioned, it works was just not very intuitive for me:

```js
planify({ exit: true, reporter: argv.reporter })
    .step('Compiling server', (data) => {
        data.buildingServer = buildServer({ env: 'dev' });
        return data.buildingServer;
    })
    .step('Running server', (data) => {
        return data.buildingServer.then((serverRender) => runServer(serverRender));
    })
    .run();
```

Thank you for the help 👍

**Comment by satazor** [comment]
Great! Regarding not being intuitive, do you have any suggestions?

**Comment by pedro93** [comment]
From the README I noticed there is a second argument ```done``` but from testing I noticed if you pass a parameter to it, its to reject. 
Perhaps adding an additional parameter to be the ```resolved``` counterpart to ```done``` for rejecting, which would pass data between steps. This is a very rough ideia but maybe:

```js
.step('Callback step', (data, resolve, done) => resolve(AsyncFunc()) //passing the AsyncFunc resolved data to the next step
.step('Second Callback step', function(data, resolved, done){ //resolved AsyncFunc result
    console.log("here is the resolved AsyncFunc result", resolved.data);
}, function(data, resolved, done){ //reject AsyncFunc result
    console.log("the function AsyncFunc failed....", done.data);
})
```
Something like what HTML5 promises do? 
What do you think @satazor.
